<a href="https://colab.research.google.com/github/hazerr/mlzoomcamp/blob/main/homework1_mlzoomcap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1

In [2]:
import pandas as pd


In [3]:
pd.__version__

'1.5.3'

In [35]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv")


In [37]:
print(df)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  media

Question 2

In [5]:
# Obtiene el número de columnas
num_cols = len(df.columns)

print(num_cols)

10


Question 3

In [6]:
# Obtener el número de columnas
num_cols = len(df.columns)
print(num_cols)

# Obtener las columnas con valores vacíos o nulos
null_cols = df.isnull().sum()
null_cols = null_cols[null_cols > 0]
print(null_cols)

10
total_bedrooms    207
dtype: int64


Question 4

In [7]:
print(df['ocean_proximity'].unique().shape[0])

5


Question 5

In [38]:
# Filter for houses located near the bay
df_filtered5 = df[df['ocean_proximity'] == "NEAR BAY"]

# Calculate the average value of median_house_value
average_value = df_filtered5['median_house_value'].mean()

# Print the average value
print(average_value)

259212.31179039303


Question 6

In [9]:
# Calculate the average of total_bedrooms
average_bedrooms = df['total_bedrooms'].mean()

# Print the average bedrooms
print(average_bedrooms)

537.8705525375618


In [10]:
# Calculate the average of total_bedrooms
average_bedrooms = df['total_bedrooms'].mean()

# Fill the missing values in total_bedrooms with the mean value
df['total_bedrooms'].fillna(average_bedrooms, inplace=True)

# Print the dataframe
print(df)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  media

In [11]:
# Obtener las columnas con valores vacíos o nulos
null_cols1 = df.isnull().sum()
null_cols1 = null_cols[null_cols1 > 0]
print(null_cols1)

Series([], dtype: int64)


Question 7

In [21]:
# Select all the options located on islands
df_filtered = df[df['ocean_proximity'] == "ISLAND"]

# Print the dataframe
print(df_filtered)

      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318         

In [22]:
# Select only columns housing_median_age, total_rooms, total_bedrooms
df_filtered = df[['housing_median_age', 'total_rooms', 'total_bedrooms']]

# Print the dataframe
print(df_filtered)

       housing_median_age  total_rooms  total_bedrooms
0                    41.0        880.0           129.0
1                    21.0       7099.0          1106.0
2                    52.0       1467.0           190.0
3                    52.0       1274.0           235.0
4                    52.0       1627.0           280.0
...                   ...          ...             ...
20635                25.0       1665.0           374.0
20636                18.0        697.0           150.0
20637                17.0       2254.0           485.0
20638                18.0       1860.0           409.0
20639                16.0       2785.0           616.0

[20640 rows x 3 columns]


In [23]:
# Get the underlying NumPy array
X = df_filtered.to_numpy()

# Print the array
print(X)

[[  41.  880.  129.]
 [  21. 7099. 1106.]
 [  52. 1467.  190.]
 ...
 [  17. 2254.  485.]
 [  18. 1860.  409.]
 [  16. 2785.  616.]]


In [24]:
import numpy as np
# Transpose X
X_T = X.T

# Compute XTX
XTX = np.matmul(X_T, X)

# Print the array
print(XTX)

[[2.01984850e+07 1.35332892e+09            nan]
 [1.35332892e+09 2.41621366e+11            nan]
 [           nan            nan            nan]]


In [25]:
XTX_inv = np.linalg.inv(XTX)
print(XTX_inv)

[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]


In [26]:
y = np.array([950, 1300, 800, 1000, 1300])


In [28]:
w = np.matmul(XTX_inv, X_T)

# Multiply the result by y
print(w)

[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


In [33]:
import numpy as np

# Read the housing.csv file using pandas
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv")

# Select all the options located on islands
df_filtered = df[df['ocean_proximity'] == "ISLAND"]

# Select only columns housing_median_age, total_rooms, total_bedrooms
df_filtered = df_filtered[['housing_median_age', 'total_rooms', 'total_bedrooms']]

# Get the underlying NumPy array
X = df_filtered.to_numpy()

# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = np.matmul(X.T, X)

# Compute the inverse of XTX.
XTX_inv = np.linalg.inv(XTX)

# Create an array y with values [950, 1300, 800, 1000, 1300].
y = np.array([950, 1300, 800, 1000, 1300])

# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = np.matmul(XTX_inv, X_T)

# Print the array w
print(w[-1])

[-0.00918146 -0.08429547 -0.01872098 ... -0.01270076 -0.00937933
 -0.01427538]
